# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Travis Alongi
email: talongi@usgs.gov
description:   # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
github_username: travisalongi
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 6 # amount of posts to show
paginate_path: /page:num/
timezone: PST # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-feed

author:
  name   : "Travis Alongi"
  avatar : "/assets/Images/me_larger_gitsite.png"
  bio    : "Mendenhall Research Geophysicists,  US Geological Survey"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:talongi@usgs.gov"
    - label: "CV"
      icon: "far fa-fw fa-file-pdf"
      url: "/assets/Files/ta_curriculum_vitae_2024-04-03.html"
    - label: "Google Scholar"
      icon: "fab fa-google"
      url: "https://scholar.google.com/citations?user=th56MtgAAAAJ&hl=en&oi=ao"
#    - label: "Twitter"
      #icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/AlongiTravis"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/travisalongi"
    - label: "USGS - ESC"
      icon: "fas fa-fw fa-link"
      url: "https://www.usgs.gov/centers/earthquake-science-center"

footer:
  links:



defaults:
  # _posts
  - scope:
      path: "_posts"
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
