#+TITLE: Travis Alongi Curriculum Vitae <2021-08-25 Wed>
#+AUTHOR: Travis Alongi

* Research Interests:
Offshore faults, fault damage zones, subduction zone seismology, seismic and aseismic slip.

* Education:
+ PhD, Earth and Planetary Science (Expected graduation 2023)
  - University of California, Santa Cruz

+ UC Extension program - Earth Science Coursework
  - University of California, Santa Cruz [GPA 4.0]

+ Geology, Science, Mathematics
  - Cabrillo College, Aptos, CA [GPA 3.7]

+ Bachelor of Science, Business (Dec. 2007)
    - San Jose State University, CA [GPA 3.52] Dean’s Scholar

* Research Experience:
+ Using 3D Seismic Data to Study the Offshore Damage Zones, Kinematics and Earthquakes in the Palos Verdes Fault Region
  - UC Santa Cruz and USGS Pacific Marine Coastal Science Center (8/2019 - Current)

+ Exploring seismicity of Southernmost Cascadia Subduction Zone Using Dense Seismic Network Including Ocean Bottom Seismometers
  - Institute for Geophysics and Planetary Physics, UC Santa Cruz, CA (1/2018 - 3/2021)

+ Refining Slab Geometry & Geodynamic Models of the Tonga Subduction Zone
  - Scripps Institute of Oceanography, La Jolla, CA (7/2017-10/2017)

* Presentations:
+ Using Active Source Seismology to Image a Strike-Slip Fault Damage Zone as a Function of Depth, Distance, and Geology
  - 3rd Cargese Earthquakes School (Corsica, France)
  - 10/2021 Virtual Meeting

+ Using Active Source Seismology to Image a Strike-Slip Fault Damage Zone as a Function of Depth, Distance, and Geology
  - Southern California Earthquake Center Annual Meeting
  - 9/2021 Virtual Meeting

+ Probing the Southern Cascadia Plate Interface with a Dense Amphibious Cascadia Initiative Seismic Array (talk)
  - GAGE-SAGE Community Science Workshop
  - 8/2021 Virtual Meeting

+ Probing the Southern Cascadia Plate Interface with a Dense Amphibious Cascadia Initiative Seismic Array (talk)
  - Northern California Earthquake Hazards Workshop
  - 2/2021 Virtual Meeting

+ Probing the Southern Cascadia Plate Interface with a Dense Amphibious Cascadia Initiative Seismic Array (talk)
  - American Geophysical Union Conference
  - 12/2020 Virtual Meeting

+ Fault Damage Zones in 3D with Active-Source Seismic Data (poster)
  - American Geophysical Union Conference
  - 12/2019 San Francisco, CA

+ Fault Damage Zones in 3D with Active-Source Seismic Data (poster)
  - Southern California Earthquake Center Annual Meeting
  - 9/2019 Palm Springs, CA

+ Using the Cascadia Initiative to Investigate Seismicity and Possible Shallow Slow Slip Along the Southernmost Section of the Cascadia Subduction Zone. (poster)
  - American Geophysical Union Conference
  - 12/2018 Washington D.C.

+ Refining the Tonga Slab Geometry Using Slab Phases of Seismic Waves
  - American Geophysical Union Conference (poster)
  - 12/2017 New Orleans, LA

* Honors and Awards:
+ 2021 Zhen and Ren Wu Memorial Fund
+ 2020 Eli Silver EPS Opportunities Fund
+ 2017 IRIS Summer Internship
+ 2016 Henry A Martin Scholarship

* Teaching Experience:
+ Teaching assistant, Geology of National Parks (4/2019 - 7/2019)
    - University of California, Santa Cruz, CA
+ Teaching assistant, Environmental Geology (4/2020 - 7/2020)
    - University of California, Santa Cruz, CA
+ Student assistant, California Historical Geology (1/2016 – 7/2016)
    - Cabrillo College, Aptos, CA

* Relevant Coursework:
Earthquake Physics, Crustal Deformation, Order of Magnitude Estimation, The Dynamic Earth, Practical Geophysics, Seismotectonics, Machine Learning for Geophysicists, Topics in Geophysics, Scientific Computing, Foundations in Applied Mathematics, Structural Geology, Data Analysis in Earth Science, Foundations in Earth Science.
